### PR TITLE
LPS-121474 Make sure Liferay process can respond to SIGTERM. For appr…

### PR DESCRIPTION
**Pull request by timscottbell**
…oach, see https://unix.stackexchange.com/questions/146756/forward-sigterm-to-child-in-bash as well as http://veithen.io/2014/11/16/sigterm-propagation.html.

### CODE REVIEW

**Comment by timscottbell** [comment]
@allen-ziegenfus @arbetts . WIP and I need to test it as well. We will also need to make sure we add `exec` to our LiferayCloud images since we're overriding `start_liferay.sh`. The solution is more complex than I'd like it to be, but seems to be an accepted solution.

Do we know what the use case of  `execute_scripts /usr/local/liferay/scripts/post-shutdown` is? I see that on the cloud side we're not currently even using this.

**Comment by arbetts** [comment]
@allen-ziegenfus is currently trying to use this to send a notification that the instance shut down, which I'd like to include into our services alerts/activities

**Comment by timscottbell** [comment]
Yes @arbetts and I've sent a PR to update our Liferay image.

**Comment by allen-ziegenfus** [comment]
@timscottbell  Yes I wanted to see a notification when hosts shut down.

Another use case I thought of was preserving log files on shutdown, since right now they just disappear

**Comment by timscottbell** [comment]
@zsoltbalogh I've tested this, and it's working.

**Comment by zsoltbalogh** [comment]
It was merged earlier, closing. Thank you!

**Pull request closed without merging**
