### PR TITLE
LPS-102834 Fixed bash binary operator expected

### PR DESCRIPTION
**Pull request by amusarra**
Fixed the if expression /usr/local/bin/configure_liferay.sh: line 12: [: portal-ext.properties: binary operator expected

### CODE REVIEW

**Comment by amusarra** [comment]
Hi @zsoltbalogh.
Do you know who will deal with this problem introduced a few days ago? The image published on Docker Hub is not 100% usable.

Thanks,
Antonio.

**Comment by mdelapenya** [comment]
It would be great adding a test before building the image 🤔 

Wdyt?

**Comment by zsoltbalogh** [comment]
I'll look into this today. Thank you!

**Comment by amusarra** [comment]
Hi @zsoltbalogh 
With the last push I corrected the error to convert the date for Darwin in case the language is different from en_US. I also added the dynamic VCS_URL parameter to build local images. As soon as I have time I will write a README.

**Comment by zsoltbalogh** [comment]
Thank you, @amusarra ! Please check the last versoin of README.md, I have started one earlier, it was just deleted.

**Comment by amusarra** [comment]
@zsoltbalogh Why was the README removed?

**Comment by zsoltbalogh** [comment]
@amusarra , before I can accept your PR (I'd really like to merge), could you please add the link to this ticket and move the ticket to Solution Contributed status?
https://issues.liferay.com/browse/LPS-102834

We are working on enabling a workflow here on github to accept contributions, however it's not live yet for this project, unfortunately.

**Comment by zsoltbalogh** [comment]
@amusarra We are working on making improvements on how docker images are built internally and we would like to sync up with the documentation at the same time. It was removed as until the process is completed it might become out of sync and we are making changes to the docker hub descriptions directly instead. Once (in some weeks hopefully) we have all the major changes in place, we will be able to link the official docs in the README.

**Comment by zsoltbalogh** [comment]
Aaaand, I've thought I already said this, but haven't. Thank you for the fix, I really appreciate for taking the time to address this issue I've put in!

**Comment by zsoltbalogh** [comment]
@mdelapenya we are working on improving our processes, actually this is the reason why we are making these changes to the repository.

**Comment by zsoltbalogh** [comment]
Awesome, thank you for making the changes to the LPS, I'll review the code tonight!

**Comment by amusarra** [comment]
@zsoltbalogh PR modified and add contribution solutions on issue LPS-102834. 
For other contribution, I will proceed with open the LPS issue and then with pull request.

**Comment by zsoltbalogh** [comment]
I reviewed the PR and forwarded the majority to @brianchandotcom:
https://github.com/brianchandotcom/liferay-docker/pull/15

I had some minor changes only, mostly source formatting. Thank you for your contribution!

**Pull request closed without merging**
