### PR TITLE
LPS-102849 Docker: Add the option push on Docker Hub for image local build

### PR DESCRIPTION
**Pull request by amusarra**
It is useful to have the ability to build local images and then push them to your Docker Hub account.

```
Usage: ./build_local_image.sh path-to-bundle image-name version <push>
Example: ./build_local_image.sh ../bundles/master portal-snapshot demo-cbe09fb0 <push>
```

Sample Local Build of the Liferay 7.2 CE (with SQL Server Support) and push on my Docker Hub account
```
./build_local_image.sh ~/dev/liferay-ce-portal-7.2.0-ga1/ amusarra/liferay-portal-72-ga1-sqlserver 7.2-ga1-sqlserver push
```

Referer commit [Added docker push option on build local image](https://github.com/liferay/liferay-docker/commit/1dd1f2061b853fd6c12e4a3bc5daf7f131356080)

### CODE REVIEW

**Comment by amusarra** [comment]
Hi @zsoltbalogh the referer commit for this pull request is [Added docker push option on build local image](https://github.com/liferay/liferay-docker/commit/1dd1f2061b853fd6c12e4a3bc5daf7f131356080)

**Comment by zsoltbalogh** [comment]
@amusarra , this PR is on my list to review, unfortunately I'm on a slow connection (on holiday) this and next week so I cannot really test, I'm hoping it's okay if I only check this on the week of the 4th of Nov.

**Comment by amusarra** [comment]
Don’t worry, It’s ok.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by amusarra** [comment]
Hi @gamerson 
How is the review going? Let me know in case of clarifications.

Thanks.

**Comment by gamerson** [comment]
hey @amusarra  could you rebase on top of latest master? and resend?  That will make the commit trail easy to review.  Thanks

**Comment by amusarra** [comment]
Hi @gamerson 
Now everything should be OK. Thanks

**Comment by zsoltbalogh** [comment]
@amusarra , thank you for the contribution again and sorry for taking so long! 

I have forwarded your PR to Brian to review: https://github.com/brianchandotcom/liferay-docker/pull/25

At Liferay we always work on clean merges so when we before send pull requests we rebase our PRs on top of latest master (or specific branch). This way we can always keep a clean history. If you are planning to contribute more, it would be great if you could also start your contributions from a new branch which is freshly forked off, that would help a lot with code reviews. 

Thank you for your help again!

**Pull request closed without merging**
